"""Import schema.

Revision ID: 0d5ce6320883
Revises: 
Create Date: 2020-03-22 14:38:03.868388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5ce6320883'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bands',
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('band_id')
    )
    op.create_table('disks',
    sa.Column('disk_id', sa.Integer(), nullable=False),
    sa.Column('disk_name', sa.String(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('incl', sa.Float(), nullable=True),
    sa.Column('PA', sa.Float(), nullable=True),
    sa.Column('PA_gofish', sa.Float(), nullable=True),
    sa.Column('T_eff', sa.Float(), nullable=True),
    sa.Column('L_star', sa.Float(), nullable=True),
    sa.Column('M_star', sa.Float(), nullable=True),
    sa.Column('logMdot', sa.Float(), nullable=True),
    sa.Column('v_sys', sa.Float(), nullable=True),
    sa.Column('CO_ext', sa.Float(), nullable=True),
    sa.Column('RA_center', sa.String(), nullable=True),
    sa.Column('Dec_center', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('disk_id'),
    sa.UniqueConstraint('disk_name')
    )
    op.create_table('molecules',
    sa.Column('molecule_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('molecule_name'),
    sa.UniqueConstraint('molecule_name')
    )
    op.create_table('setups',
    sa.Column('setup_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('setup_id')
    )
    op.create_table('spws',
    sa.Column('spw_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('spw_id')
    )
    op.create_table('transitions',
    sa.Column('transition_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Float(), nullable=False),
    sa.Column('mol_id', sa.String(), nullable=True),
    sa.Column('quantum_number', sa.String(), nullable=True),
    sa.Column('spw_id', sa.Integer(), nullable=True),
    sa.Column('band_id', sa.Integer(), nullable=True),
    sa.Column('setup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['band_id'], ['bands.band_id'], ),
    sa.ForeignKeyConstraint(['mol_id'], ['molecules.molecule_name'], ),
    sa.ForeignKeyConstraint(['setup_id'], ['setups.setup_id'], ),
    sa.ForeignKeyConstraint(['spw_id'], ['spws.spw_id'], ),
    sa.PrimaryKeyConstraint('transition_id'),
    sa.UniqueConstraint('frequency')
    )
    op.create_table('measurement_sets',
    sa.Column('transition_id', sa.Integer(), nullable=False),
    sa.Column('disk_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('ingested', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['disk_id'], ['disks.disk_id'], ),
    sa.ForeignKeyConstraint(['transition_id'], ['transitions.transition_id'], ),
    sa.PrimaryKeyConstraint('disk_id', 'transition_id', 'version', name='ms_id'),
    sa.UniqueConstraint('path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurement_sets')
    op.drop_table('transitions')
    op.drop_table('spws')
    op.drop_table('setups')
    op.drop_table('molecules')
    op.drop_table('disks')
    op.drop_table('bands')
    # ### end Alembic commands ###
