"""adding cubes table.

Revision ID: 11b59df61e4e
Revises: df88255c79ea
Create Date: 2020-03-24 22:19:52.899871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b59df61e4e'
down_revision = 'df88255c79ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cubes',
    sa.Column('cube_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('disk_id', sa.Integer(), nullable=False),
    sa.Column('transition_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('method_type', sa.String(), nullable=True),
    sa.Column('method_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['disk_id', 'transition_id', 'version'], ['measurement_sets.disk_id', 'measurement_sets.transition_id', 'measurement_sets.version'], name='ms_id'),
    sa.ForeignKeyConstraint(['method_type', 'method_version'], ['method_implementations.method_type', 'method_implementations.method_version'], name='method_implementation_id'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('cube_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cubes')
    # ### end Alembic commands ###
