"""trying to autogenerate runs

Revision ID: 47a0ac9c4af7
Revises: a374824947ce
Create Date: 2020-03-24 22:06:19.807390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a0ac9c4af7'
down_revision = 'a374824947ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('runs_id', sa.Integer(), nullable=False),
    sa.Column('run_status', sa.Integer(), nullable=True),
    sa.Column('job_array_id', sa.Integer(), nullable=True),
    sa.Column('slurm_id', sa.Integer(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('output_dir', sa.String(), nullable=True),
    sa.Column('channel_start', sa.Integer(), nullable=True),
    sa.Column('channel_end', sa.Integer(), nullable=True),
    sa.Column('parameter_id', sa.Integer(), nullable=True),
    sa.Column('disk_id', sa.Integer(), nullable=False),
    sa.Column('transition_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('method_type', sa.String(), nullable=True),
    sa.Column('method_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['disk_id', 'transition_id', 'version'], ['measurement_sets.disk_id', 'measurement_sets.transition_id', 'measurement_sets.version'], name='ms_id'),
    sa.ForeignKeyConstraint(['method_type', 'method_version'], ['method_implementations.method_type', 'method_implementations.method_version'], name='method_implementation_id'),
    sa.ForeignKeyConstraint(['parameter_id'], ['parameters.parameter_id'], ),
    sa.ForeignKeyConstraint(['run_status'], ['run_statuses.run_status_id'], ),
    sa.PrimaryKeyConstraint('runs_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runs')
    # ### end Alembic commands ###
