"""added cube and runs

Revision ID: a374824947ce
Revises: 0d5ce6320883
Create Date: 2020-03-24 17:31:13.456107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a374824947ce'
down_revision = '0d5ce6320883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cube_types',
    sa.Column('cube_type_id', sa.Integer(), nullable=False),
    sa.Column('cube_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cube_type_id')
    )
    op.create_table('img_types',
    sa.Column('img_type_id', sa.Integer(), nullable=False),
    sa.Column('img_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('img_type_id')
    )
    op.create_table('method_types',
    sa.Column('method_type_id', sa.Integer(), nullable=False),
    sa.Column('method_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('method_type_id'),
    sa.UniqueConstraint('method_type')
    )
    op.create_table('parameters',
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.Column('npix', sa.Integer(), nullable=True),
    sa.Column('cell_size', sa.Float(), nullable=True),
    sa.Column('n_opt', sa.Integer(), nullable=True),
    sa.Column('loss_rate', sa.Float(), nullable=True),
    sa.Column('penalty_entropy', sa.Float(), nullable=True),
    sa.Column('penalty_tsv', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('parameter_id')
    )
    op.create_table('run_statuses',
    sa.Column('run_status_id', sa.Integer(), nullable=False),
    sa.Column('run_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('run_status_id'),
    sa.UniqueConstraint('run_status')
    )
    op.create_table('method_implementations',
    sa.Column('method_type', sa.String(), nullable=False),
    sa.Column('method_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['method_type'], ['method_types.method_type'], ),
    sa.PrimaryKeyConstraint('method_type', 'method_version', name='method_implementation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('method_implementations')
    op.drop_table('run_statuses')
    op.drop_table('parameters')
    op.drop_table('method_types')
    op.drop_table('img_types')
    op.drop_table('cube_types')
    # ### end Alembic commands ###
